### ISSUE TITLE
Failed to allocate the clone RAM buffer

### ISSUE THREAD

**Issue by qfrtt** [kweatherman/sigmakerex#10]
Hello,

I am getting this error it's completely random sometimes the sig maker plugin works and sometimes not.

```
SigMakerEx: Finding function signature.
SigMakerEx: ** Failed to allocate the clone RAM buffer of size: 0xFFFFF77F80021000 ! **
SigMakerEx: * Failed to find a base or reference signature for selected function. *
```
Tested on IDA 7.7 and 8.3

**Comment by kweatherman** [comment]
Thanks for pointing this out. The RAM error is strange, appears to get a signed number.
`SigMakerEx: * Failed to find a base or reference signature for selected function. *` this one is normal though. It's saying that the function is not unique and it can't find a unique referencing function.

Take a look..
I don't have your IDB so complicates troubleshooting this.
The error is at [Search.cpp#L38)](https://github.com/kweatherman/sigmakerex/blob/master/Search.cpp#L38).

Okay not thinking this was even possible, but put in that msg to catch it, it first fails in the copy so yea the match operation will fail as well. Ignore the match result. We focus on the clone error. 

Is this in a live IDB debugging session? 
Is the IDB rebased? It shouldn't matter but apparently somehow the the `inf.min_ea` is larger than the `inf.max_ea` hence the resulting signed `size`.

Go to options and turn on the verbose output mode.
Let's see what the above .."min_ea: 0x%llX, max_ea: 0x%llX, size: 0x%llX".. line outputs.

**Comment by qfrtt** [comment]
> The RAM error is strange, appears to get a signed number. `SigMakerEx: * Failed to find a base or reference signature for selected function. *` this one is normal though. It's saying that the function is not unique and it can't find a unique referencing function.
> 
> Taking a look.. I don't have your IDB so complicates troubleshooting this. The error is at [Search.cpp#L38](https://github.com/kweatherman/sigmakerex/blob/master/Search.cpp#L38).
> 
> Okay not thinking this was even possible, but put in that msg to catch it, it first fails in the copy so yea the match operation will fail as well. Ignore the match result. Focus on the clone error.
> 
> Is this in a live IDB debugging session? Is the IDB rebased? It shouldn't matter but apparently somehow the the `inf.min_ea` is larger than the `inf.max_ea` hence the resulting signed `size`.
> 
> Go to options and turn on the verbose output mode. Let's see what the above [#L16](https://github.com/kweatherman/sigmakerex/blob/master/Search.cpp#L16) .."min_ea: 0x%llX, max_ea: 0x%llX, size: 0x%llX".. line outputs.

Hello, sorry for the late reply. I reanalyzed the IDB and the problem was solved.

**Comment by kweatherman** [comment]
Mo problem glad it was resolved. Sounds like the DB was broken.

**Comment by tawnix** [comment]
Just so you know, I tried the above solution. I'm still getting the RAM error:
`SigMakerEx: Finding signature for 00000140379FE0.
SigMakerEx: ** Failed to allocate the clone RAM buffer of size: 0xFFFFF77F80021000 ! **
SigMakerEx: * Failed to find unique signiture at address. *`

**Comment by kweatherman** [comment]
Probably easier if you just opened a new issue since this one was closed. If you're a different person, the OP will probably get an email about it too.

Anyhow, it looks like the same problem too. Being a corrupt IDB. 
So some of the same questions. Is in a live debugger session?
What version of IDA is this?

Looks like this is from some sort of memory dump too (vs loading a functional PE file like an ".exe" from disk).
If it's a memory dump, you probably need to fix the PE header.

Just think for a minute, does `SearchData::CloneIdb: min_ea: 0x7FFE0000, max_ea: 0xFFFFF78000001000, size: 0xFFFFF77F80021000` look valid to you?

It would take at least 16,777,208 terabytes  (1,073,741,824 gigabytes) to just store this image on disk or load it into RAM.
Must have taken IDA ages to load..

**Comment by tawnix** [comment]
> You should have opened a new issue since this one was closed. If you're a different person, the OP will probably get an email about it too.
> 
> 
> 
> Anyhow, it looks like the same problem too. Being a corrupt IDB. 
> 
> So some of the same questions. Is in a live debugger session?
> 
> What version of IDA is this?
> 
> 
> 
> Looks like this is from some sort of memory dump too (vs loading a functional PE file like an ".exe" from disk).
> 
> If it's a memory dump, you probably need to fix the PE header.
> 
> 
> 
> Just think for a minute. Does `SearchData::CloneIdb: min_ea: 0x7FFE0000, max_ea: 0xFFFFF78000001000, size: 0xFFFFF77F80021000` look valid to you? IDA is telling you, the size of the IDB is 18,446,734,997,852,647,424.
> 
> 
> 
> It would take at least 16,777,208 terabytes  (1,073,741,824 gigabytes) to just store this image on disk or load it into RAM.
> 
> Must have taken IDA ages to load..
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 

Hi, thank you for replying.

1. No this is not in a debugger session.

2. This is not a memory dump it's just ntoskrnl loaded from disk not memory.

3. Yes I can see the size is terabytes lol. 


This plugin worked great before, it just randomly started doing this. Which is why I commented on this post. And it only took IDA 5-10min to load

**Comment by kweatherman** [comment]
Works for me! (old developer joke):
![image](https://github.com/kweatherman/sigmakerex/assets/76711484/927eef8b-1971-4c74-a46f-30cda69b85f5)

Np, took no offense. Was being funny about it.

But then an older version of Windows 10 64bit.
I don't doubt you're having a problem, just trying to figure out why.

What version of the one you are looking at?
![image](https://github.com/kweatherman/sigmakerex/assets/76711484/02c40e73-fbb7-4b11-9585-c470fd6e01c9)

What version of IDA?
Any other plugins active? 
I wonder, the assumption is for any PE file is that they load in one contagious chunk. For any Windows module there is a base address and length basically. The process is built from a series of segments with virtual addresses.
I wouldn't think it was possible to have segments that jump around over different memory spaces.

Copy a screen shot of the segments.
Like this one, which is for this particular dump:  
![image](https://github.com/kweatherman/sigmakerex/assets/76711484/d38bd7e3-ed65-48cf-883b-b2cf707ad3a7)

**Comment by tawnix** [comment]
> Works for me! (old developer joke): ![image](https://private-user-images.githubusercontent.com/76711484/291263626-927eef8b-1971-4c74-a46f-30cda69b85f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MDI4NDQsIm5iZiI6MTcwMjkwMjU0NCwicGF0aCI6Ii83NjcxMTQ4NC8yOTEyNjM2MjYtOTI3ZWVmOGItMTk3MS00Yzc0LWE0NmYtMzBjZGE2OWI4NWY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDEyMjkwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNWRkNjMxZDBhYTFhNDI1ZWM5MmU4NDI5NjQ5OWUxOTBlNDcwNWUzMGFlNDBhMDMxMGFjZjg1YzI0NjFiMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lkt3Um3aINJKRYUFD-JQJGUU023Zp3YVzh2vvoliQeI)
> 
> Np, took no offense. Was being funny about it.
> 
> But then an older version of Windows 10 64bit. I don't doubt you're having a problem, just trying to figure out why.
> 
> What version of the one you are looking at? ![image](https://private-user-images.githubusercontent.com/76711484/291264192-02c40e73-fbb7-4b11-9585-c470fd6e01c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MDI4NDQsIm5iZiI6MTcwMjkwMjU0NCwicGF0aCI6Ii83NjcxMTQ4NC8yOTEyNjQxOTItMDJjNDBlNzMtZmJiNy00YjExLTk1ODUtYzQ3MGZkNmUwMWM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDEyMjkwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3ZjM2ZjU0YTY0MTI1OWY5N2YwYzY2MDdlZTkwNTFlZTU2ZDJjYTdmNjIxMDIyZDkzZmYyYjJlY2RlZGU3NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OtGgn2zhZXh1OLVtGzG5wD2uTKeW6BXZI38T5bagjJQ)
> 
> What version of IDA? Any other plugins active? I wonder, the assumption is for any PE file is that they load in one contagious chunk. For any Windows module there is a base address and length basically. The process is built from a series of segments with virtual addresses. I wouldn't think it was possible to have segments that jump around over different memory spaces.
> 
> Copy a screen shot of the segments. Like this one, which is for this particular dump: ![image](https://private-user-images.githubusercontent.com/76711484/291265545-d38bd7e3-ed65-48cf-883b-b2cf707ad3a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MDI4NDQsIm5iZiI6MTcwMjkwMjU0NCwicGF0aCI6Ii83NjcxMTQ4NC8yOTEyNjU1NDUtZDM4YmQ3ZTMtZWQ2NS00OGNmLTg4M2ItYjJjZjcwN2FkM2E3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDEyMjkwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmZDFkNDJkODgxZmE1Mzk0OTUyNjc3MDVlNGViMTdlMGVjODgxMTRlNjdhZWU0ZmRiZGUxMTRlNmI4ZjIwM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t9pYlKTUANCN8SPNjXrSm8Ee5LXHkeJE_sK1KdAGGZk)

Thanks for replying and helping.



My Ntos version:
![ntos version](https://github.com/kweatherman/sigmakerex/assets/20980231/92eb4ca3-ca79-4f77-a52d-67e85f7ec059)


IDA Version: IDA Pro 7.7

Active Plugins: ClassInformer & SigMakerEx (Plus all the other default shit in the plugins folder)


PE Segments:

![ida](https://github.com/kweatherman/sigmakerex/assets/20980231/aa20cf07-9e99-409e-a079-e80194595432)

**Comment by kweatherman** [comment]
Okay, there it is. Didn't even know this was even possible with the PE format.

Windows 10 right? And looks like a most recent update. Update to 22H2?
I'm trying to find the same exact version. 

Maybe it's a thing, but don't recall seeing a PE file with broken up different address blocks in 20 plus years.
Maybe shared memory segments with a specified address.
Again trying to get the same version, but is there any data in those segments or just uninitialized filter bytes?
Anything has references in or out of those two extreme segments?
Notice they are both only a page in size.

Will have to get a copy and think about how to handle these. I would imagine it will break any other tool that uses the min/max address range including a lot of IDA's own sample scripts and plugins.

For now, you can probably just go to Edit -> Segments -> "Delete segment.." on those two. If just uninitialized data, it will make no difference.

**Comment by tawnix** [comment]
Yea its windows 10 22H2, I did upgrade to windows pro, maybe that could be why?



I'll have to check if there is data in these segments. I'll post a new comment when I do so.

**Comment by tawnix** [comment]
Yes this actually worked deleting the segments, and a signature is created again with ease. Such an easy fix lol, thanks alot.

Just so you know this bug does not just happen with ntoskrnl.exe it happens with any file thats dropped inside of IDA.

**Comment by qfrtt** [comment]
I forgot to mention yeah a temp fix was just deleting those segments because I saw they were there, but magically after reanalysing the idb they were gone.

**Comment by kweatherman** [comment]
Good to know. Deleting those odd segments at the end should affect anything.
I'm sure I'll run into that version of ntoskrnl.exe soon and try it in IDA 8.x
